---
# Remove eucalyptus packages and configuration (including dependencies)
- name: disable eucalyptus-cloud service
  systemd:
    enabled: false
    state: stopped
    name: eucalyptus-cloud
  register: systemd_result
  failed_when: "systemd_result is failed and 'Could not find the requested service' not in systemd_result.msg"

- name: disable eucalyptus-node service
  systemd:
    enabled: false
    state: stopped
    name: eucalyptus-node
  register: systemd_result
  failed_when: "systemd_result is failed and 'Could not find the requested service' not in systemd_result.msg"

- name: disable eucanetd service
  systemd:
    enabled: false
    state: stopped
    name: eucanetd
  register: systemd_result
  failed_when: "systemd_result is failed and 'Could not find the requested service' not in systemd_result.msg"

- name: disable libvirtd service
  systemd:
    enabled: false
    state: stopped
    name: libvirtd
  register: systemd_result
  failed_when: "systemd_result is failed and 'Could not find the requested service' not in systemd_result.msg"

- name: disable midonet-cluster service
  systemd:
    enabled: false
    state: stopped
    name: midonet-cluster
  register: systemd_result
  failed_when: "systemd_result is failed and 'Could not find the requested service' not in systemd_result.msg"

- name: disable midolman service
  systemd:
    enabled: false
    state: stopped
    name: midolman
  register: systemd_result
  failed_when: "systemd_result is failed and 'Could not find the requested service' not in systemd_result.msg"

- name: disable cassandra service
  systemd:
    enabled: false
    state: stopped
    name: cassandra
  register: systemd_result
  failed_when: "systemd_result is failed and 'Could not find the requested service' not in systemd_result.msg"

- name: disable zookeeper service
  systemd:
    enabled: false
    state: stopped
    name: zookeeper
  register: systemd_result
  failed_when: "systemd_result is failed and 'Could not find the requested service' not in systemd_result.msg"

- name: stop ceph target
  systemd:
    enabled: false
    state: stopped
    name: ceph.target
  register: systemd_result
  failed_when: "systemd_result is failed and 'Could not find the requested service' not in systemd_result.msg"

- name: remove eucalyptus and dependency packages
  yum:
    name:
      - eucaconsole
      - eucaconsole-selinux
      - eucalyptus
      - eucalyptus-admin-tools
      - eucalyptus-axis2c-common
      - eucalyptus-blockdev-utils
      - eucalyptus-cc
      - eucalyptus-cloud
      - eucalyptus-common-java
      - eucalyptus-common-java-libs
      - eucalyptus-imaging-toolkit
      - eucalyptus-java-deps
      - eucalyptus-nc
      - eucalyptus-sc
      - eucalyptus-selinux
      - eucalyptus-service-image
      - eucalyptus-service-image-tools
      - eucalyptus-walrus
      - eucanetd
      - euca2ools
      - libvirt-daemon
      - nginx
      - qemu-kvm-common
      - scsi-target-utils
    state: absent

- name: remove midonet and dependency packages
  yum:
    name:
      - cassandra22
      - midolman
      - midonet-cluster
      - midonet-tools
      - python-midonetclient
      - zkdump
      - zookeeper
    state: absent

- name: remove ceph packages
  yum:
    name:
      - ceph
      - ceph-base
      - ceph-common
      - ceph-deploy
      - ceph-mds
      - ceph-mon
      - ceph-osd
      - ceph-radosgw
      - ceph-release
      - ceph-selinux
      - libcephfs1
      - libcephfs2
      - librados2
      - libradosstriper1
      - python-ceph-argparse
      - python-cephfs
      - python-rados
    state: absent

- name: remove eucaconsole configuration directory
  file:
    path: /etc/eucaconsole
    state: absent

- name: remove eucalyptus configuration directory
  file:
    path: /etc/eucalyptus
    state: absent

- name: remove eucalyptus libexec directory
  file:
    path: /usr/libexec/eucalyptus
    state: absent

- name: remove eucalyptus share directory
  file:
    path: /usr/share/eucalyptus
    state: absent

- name: remove eucalyptus state directory
  file:
    path: /var/lib/eucalyptus
    state: absent

- name: remove midolman configuration directory
  file:
    path: /etc/midolman
    state: absent

- name: remove midolman state directory
  file:
    path: /var/lib/midolman
    state: absent

- name: remove midonet configuration directory
  file:
    path: /etc/midonet
    state: absent

- name: remove midonet-cluster configuration directory
  file:
    path: /etc/midonet-cluster
    state: absent

- name: remove midonet-cluster state directory
  file:
    path: /var/lib/midonet-cluster
    state: absent

- name: remove cassandra configuration directory
  file:
    path: /etc/cassandra
    state: absent

- name: remove cassandra share directory
  file:
    path: /usr/share/cassandra
    state: absent

- name: remove cassandra state directory
  file:
    path: /var/lib/cassandra
    state: absent

- name: remove zookeeper state directory
  file:
    path: /var/lib/zookeeper
    state: absent

- name: remove ceph configuration directory
  file:
    path: /etc/ceph
    state: absent

- name: unmount ceph temporary filesystems
  shell: |
    for CEPH_MOUNT in $(findmnt --type tmpfs --mtab --raw --noheadings | grep -oE '/var/lib/ceph/[a-zA-Z0-9_/-]+'); do
      echo "Unmounting ${CEPH_MOUNT}"
      umount "${CEPH_MOUNT}"
    done
  register: shell_result
  changed_when: '"Unmounting" in shell_result.stdout'

- name: remove provisioned ceph logical volumes
  shell: |
    for CEPH_LV_PATH in $(lvs --noheadings -o path @eucalyptus.provisioned=yes); do
      lvremove --force "${CEPH_LV_PATH}"
    done
  register: shell_result
  changed_when: '"successfully removed" in shell_result.stdout'

- name: remove ceph state directory
  file:
    path: /var/lib/ceph
    state: absent

- name: remove ceph default osd directory
  file:
    path: /var/lib/ceph-osd
    state: absent

- name: remove ceph-deploy user cluster directory
  file:
    path: /home/ceph-deploy/cluster
    state: absent

- name: remove ceph-deploy user conf file
  file:
    path: /home/ceph-deploy/.cephdeploy.conf
    state: absent

- name: remove tools configuration directory
  file:
    path: /root/.euca
    state: absent

- name: remove eucalyptus deployment configuration directory
  file:
    path: /root/eucalyptus
    state: absent

