---
- name: install dnsmasq
  yum:
    name: dnsmasq
    state: present
  tags:
    - image
    - packages

- name: set cloud dns listening port
  shell: |
    set -eu
    eval $(clcadmin-assume-system-credentials)
    euctl --region localhost dns.dns_listener_port={{ cloud_dns_listener_port | quote }}
  register: shell_result
  until: shell_result.rc == 0
  retries: 5

- name: set dnsmasq upstreams servers
  ansible.builtin.copy:
    src: /etc/resolv.conf
    dest: /etc/dnsmasq-euca.resolv
    owner: root
    group: root
    force: no
    mode: '0644'
    backup: yes

- name: set dnsmasq to delegate domain to CLC
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.d/euca.conf
    force: no
    owner: root
    group: root
    mode: '0644'

- name: start dnsmasq service
  systemd:
    enabled: true
    state: started
    name: dnsmasq

- name: disable DNS updates for NetworkManager
  lineinfile:
    path: /etc/NetworkManager/NetworkManager.conf
    line: dns=none
    regexp: ^dns=none$
    insertafter: ^\[main\]$
  register: NM_conf

- name: restart NetworkManager
  systemd:
    state: restarted
    name: NetworkManager.service
  when: NM_conf

- name: set resolv.conf to point to dnsmasq
  ansible.builtin.copy:
    src: resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    force: no
    mode: '0644'
    backup: yes

