---
# Eucalyptus playbook
- hosts: all
  gather_facts: no
  tasks:
  - import_tasks: host_groups.yml

- hosts: ceph:ceph_object_gateway:ceph_deploy
  roles:
  - ceph-host

- hosts: ceph_deploy
  roles:
  - ceph

- hosts: node
  tasks:
  - name: eucalyptus node host facts
    include_role:
      name: common
      tasks_from: host_facts

- hosts: midonet_nsdb
  roles:
  - midonet-nsdb

- hosts: cloud
  roles:
  - cloud
  - console

- hosts: zone
  roles:
  - zone

- hosts: node
  roles:
  - node

- hosts: cloud
  roles:
  - cloud-post

