---
- name: install base packages
  yum:
    name:
      - net-tools
      - rsync
      - wget
    state: present
  tags:
    - image
    - packages

- name: install firewalld package
  yum:
    name: firewalld
    state: present
  tags:
    - image
    - packages
    - firewalld
  register: firewalld_package_result
