- name: start firewalld service
  systemd:
    enabled: true
    state: started
    name: firewalld
  tags:
    - firewalld
  when: cloud_firewalld_start

- name: firewalld public interface zone
  firewalld:
    zone: "{{ cloud_firewalld_public_zone }}"
    interface: "{{ cloud_firewalld_public_interface }}"
    state: enabled
    permanent: yes
    immediate: "{{ cloud_firewalld_start }}"
  tags:
    - firewalld
  when: cloud_firewalld_public_interface is not none and cloud_firewalld_public_zone is not none

- name: firewalld cluster interface zone
  firewalld:
    zone: "{{ cloud_firewalld_cluster_zone }}"
    interface: "{{ cloud_firewalld_cluster_interface }}"
    state: enabled
    permanent: yes
    immediate: "{{ cloud_firewalld_start }}"
  tags:
    - firewalld
  when: cloud_firewalld_cluster_interface is not none and cloud_firewalld_cluster_zone is not none

- name: eucalyptus firewalld cluster zone
  template:
    src: firewalld-zone-euca-cluster.xml.j2
    dest: /etc/firewalld/zones/euca-cluster.xml
    owner: root
    group: root
    mode: 0644
  tags:
    - firewalld
  when: cloud_firewalld_cluster_cidr is not none

- name: eucalyptus firewalld cluster zone load
  command:
    cmd: firewall-cmd --permanent --new-zone euca-cluster
  tags:
    - firewalld
  register: firewalld_result
  failed_when: "firewalld_result is failed and 'NAME_CONFLICT' not in firewalld_result.stderr"
  changed_when: '"NAME_CONFLICT" not in firewalld_result.stderr'
  when: cloud_firewalld_cluster_cidr is not none

- name: firewalld default zone
  command:
    cmd: firewall-cmd --set-default-zone {{ cloud_firewalld_default_zone }}
  tags:
    - firewalld
  register: command_result
  changed_when: '"ZONE_ALREADY_SET" not in command_result.stderr'
  when: cloud_firewalld_default_zone is not none

- name: firewalld reload
  systemd:
    name: firewalld
    state: reloaded
  tags:
    - firewalld
  when: cloud_firewalld_cluster_cidr is not none and firewalld_result.changed
