---
- name: configure permissive mode selinux
  selinux:
    policy: targeted
    state: permissive
  tags:
    - image
    - selinux

- name: disable firewalld service if installed
  systemd:
    enabled: false
    name: firewalld
  tags:
    - firewalld
    - image
  when: firewalld_package_result.changed
