- name: eucalyptus gather ceph configuration
  slurp:
    path: "{{ ceph_facts_path }}/ceph.conf"
  register: slurp_result

- name: set eucalyptus ceph configuration fact
  set_fact:
    eucalyptus_ceph_conf: "{{ slurp_result.content | b64decode }}"

- name: eucalyptus gather ceph client keyring
  slurp:
    path: "{{ ceph_facts_path }}/ceph.client.eucalyptus.keyring"
  register: slurp_result

- name: set eucalyptus ceph client keyring fact
  set_fact:
    eucalyptus_ceph_keyring: "{{ slurp_result.content | b64decode }}"

- name: eucalyptus gather ceph radosgw s3 credentials
  slurp:
    path: "{{ ceph_facts_path }}/rgw_credentials.json"
  register: slurp_result

- name: set eucalyptus ceph radosgw s3 credentials fact
  set_fact:
    eucalyptus_ceph_rgw_creds: "{{ slurp_result.content | b64decode | from_json }}"

- name: set eucalyptus ceph radosgw s3 endpoint local fact
  set_fact:
    eucalyptus_ceph_rgw_endpoint: "{{ eucalyptus_ceph_rgw_host }}:7480"
  when: eucalyptus_ceph_rgw_host is defined

- name: set eucalyptus ceph radosgw s3 endpoint fact
  set_fact:
    eucalyptus_ceph_rgw_endpoint: "{{ hostvars[groups['ceph_object_gateway'][0]]['eucalyptus_host_cluster_ipv4'] }}:7480"
  when: eucalyptus_ceph_rgw_host is not defined

