---
- import_tasks: host_facts.yml

- import_tasks: yum_repos_ceph.yml

- import_tasks: base_packages.yml

- import_tasks: base_config.yml

- import_tasks: base_firewall.yml
  when: cloud_firewalld_configure

- import_tasks: ceph_facts.yml
  delegate_to: "{{ groups['ceph_deploy'][0] }}"
  run_once: yes
  when: ceph_facts
