---
- name: ceph gpg key
  copy:
    src: RPM-GPG-KEY-ceph
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-ceph
    owner: root
    group: root
    mode: 0644

- name: install ceph gpg key
  rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-ceph

- name: ceph yum repository
  template:
    src: ceph.repo.j2
    dest: /etc/yum.repos.d/ceph.repo
    owner: root
    group: root
    mode: 0644

