---
- name: eucalyptus initial tunnel zone configuration
  command:
    cmd: /usr/local/bin/eucalyptus-vpcmidotz-up.sh
  environment:
    PYTHONPATH: /usr/lib/python2.7/site-packages/WebOb-1.4.1-py2.7.egg/
    EUCA_TZ_HOST_EXTRAS: "{{ groups.node | map('extract', hostvars, ['eucalyptus_host_cluster_ipv4']) | list | sort | join(' ') }}"

- name: create eucalyptus account default vpc
  shell: |
    set -eu
    eval $(clcadmin-assume-system-credentials)
    eval $(euca-generate-environment-config --region localhost)
    if [ -z "$(euca-describe-subnets --filter default-for-az=true)" ]; then
      echo "Creating default vpc for eucalyptus account"
      euca-create-vpc $(euare-getcallerid | grep -oP "\\s*account\\s*=\\s*\\K.*\\s*")
    fi
  register: shell_result
  until: shell_result.rc == 0
  retries: 5
  changed_when: '"Creating default vpc for eucalyptus account" in shell_result.stdout'
