#!/bin/sh
# Import HTTPS key/certificate from PEM files and configure all hosts
# to use.
#
# This hook a/b switches to coordinate moving between certifcates on
# all hosts and allow manual rollback.
#
set -eo pipefail

KEY_ALIAS_A="eucalyptus-cloud-a"
KEY_ALIAS_B="eucalyptus-cloud-b"
KEY_ALIAS_PROP="bootstrap.webservices.ssl.server_alias"
SERVICE_PORT_PROP="bootstrap.webservices.port"

KEY_ALIAS_CURRENT=$(euctl -n "${KEY_ALIAS_PROP}")
KEY_ALIAS_NEXT="${KEY_ALIAS_A}"
if [ "${KEY_ALIAS_CURRENT}" = "${KEY_ALIAS_A}" ] ; then
  KEY_ALIAS_NEXT="${KEY_ALIAS_B}"
fi

TARGET_PORT=$(euctl -n "${SERVICE_PORT_PROP}")
TARGET_HOSTS=$(euserv-describe-services \
  --filter service-type=cluster \
  --filter service-type=eucalyptus \
  --filter service-type=storage \
  --filter service-type=user-api \
  --group-by-host | awk '{print $2}' | sort -u)

[ -n "${TARGET_HOSTS}" ] || { echo "No hosts found" >&2; exit 3; }

for TARGET_HOST in ${TARGET_HOSTS} ; do
  export EUCA_PROPERTIES_URL="http://${TARGET_HOST}:${TARGET_PORT}/services/Properties"
  "/usr/local/bin/eucalyptus-cloud-https-import" --alias "${KEY_ALIAS_NEXT}" "$@"
done

unset EUCA_PROPERTIES_URL
euctl "${KEY_ALIAS_PROP}"="${KEY_ALIAS_NEXT}"
