# nautilus (14.2.6) ceph-deploy fails unless python-setuptools is present
- name: install ceph base packages
  yum:
    name:
      - ceph-common
      - ceph-deploy
      - python-setuptools
    state: present

- name: ceph-deploy user
  user:
    name: ceph-deploy
    comment: Ceph deployment user
    password: '!'
    createhome: yes
    groups: wheel
    generate_ssh_key: yes
  register: user_result

- name: ceph deploy gather ssh private key
  slurp:
    path: "{{ user_result.ssh_key_file }}"
  register: slurp_result

- name: set ceph deploy ssh public key fact
  set_fact:
    eucalyptus_ceph_deploy_ssh_public_key: "{{ user_result.ssh_public_key }}"
  run_once: yes

- name: set ceph deploy ssh private key fact
  set_fact:
    eucalyptus_ceph_deploy_ssh_private_key: "{{ slurp_result.content | b64decode }}"
  run_once: yes

- name: ceph-deploy user ssh authorized key
  authorized_key:
    user: ceph-deploy
    state: present
    key_options: 'no-port-forwarding,from="10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"'
    key: "{{ eucalyptus_ceph_deploy_ssh_public_key }}"

- name: ceph-deploy user ssh public key
  copy:
    dest: "{{ user_result.ssh_key_file }}.pub"
    owner: ceph-deploy
    group: ceph-deploy
    mode: 0644
    content: "{{ eucalyptus_ceph_deploy_ssh_public_key }}"

- name: ceph-deploy user ssh private key
  copy:
    dest: "{{ user_result.ssh_key_file }}"
    owner: ceph-deploy
    group: ceph-deploy
    mode: 0600
    content: "{{ eucalyptus_ceph_deploy_ssh_private_key }}"

- name: ceph-deploy user ssh known hosts
  copy:
    dest: /home/ceph-deploy/.ssh/config
    owner: ceph-deploy
    group: ceph-deploy
    mode: 0644
    content: |
      Host {{ groups['all'] | map('extract', hostvars, ['ansible_hostname']) | list | select('defined') | sort | join(' ') }} {{ groups['all'] | map('extract', hostvars, ['ansible_fqdn']) | list | select('defined') | sort | join(' ') }} {{ groups['all'] | map('extract', hostvars, ['eucalyptus_host_cluster_ipv4']) | list | select('defined') | sort | join(' ') }}
      GlobalKnownHostsFile=/dev/null
      UserKnownHostsFile=/dev/null
      StrictHostKeyChecking=no

- name: wheel group
  group:
    name: wheel
    state: present

- name: wheel group passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: ceph-deploy cluster directory
  file:
    path: /home/ceph-deploy/cluster
    owner: ceph-deploy
    state: directory
    mode: 0755

- import_tasks: ceph_osd.yml
  when: inventory_hostname in groups.ceph
