---
- name: eucalyptus configuration script for ceph
  copy:
    src: ceph-euca-setup.sh
    dest: /root/ceph-euca-setup.sh
    owner: root
    group: root
    mode: 0755

- name: eucalyptus configuration for ceph
  command:
    chdir: /root/
    cmd: /root/ceph-euca-setup.sh
    creates: /root/eucalyptus/ceph/ceph.conf
  environment:
    EUCA_CEPH_ARTIFACTS_DIR: /root/eucalyptus/ceph
    EUCA_CEPH_RGW_UID: "{{ ceph_rgw_uid }}"
    EUCA_CEPH_SNAPSHOT_POOL_NAME: "{{ ceph_osd_snapshot_pool }}"
    EUCA_CEPH_VOLUME_POOL_NAME: "{{ ceph_osd_volume_pool }}"
    EUCA_POOL_PLACEMENT_GROUPS: "{{ ceph_osd_pool_pgnum }}"

