---
- name: install bridge-utils package
  yum:
    name:
      - bridge-utils
    state: present
  tags:
    - image
    - packages

- name: create bridge interface
  template:
    src: ifcfg-brX.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ net_bridge_interface }}"
    force: no
    owner: root
    group: root
    mode: 0644

- name: bridge interface up
  command:
    cmd: "/usr/sbin/ifup {{ net_bridge_interface }}"
  register: command_result
  changed_when: "command_result is succeeded and command_result.stdout  != ''"

- name: install midolman and dependency packages
  yum:
    name:
      - java-1.8.0-openjdk-headless
      - midolman
    state: present
  tags:
    - image
    - packages

- name: midolman configuration
  template:
    src: midolman.conf.j2
    dest: /etc/midolman/midolman.conf
    owner: root
    group: root
    mode: 0644

- name: midolman memory
  replace:
    path: /etc/midolman/midolman-env.sh
    regexp: '^MAX_HEAP_SIZE=".+"$'
    replace: 'MAX_HEAP_SIZE="{{ midonet_midolman_heap }}"'
  when: midonet_midolman_heap is not none

- name: midolman systemd drop-in directory
  file:
    path: /etc/systemd/system/midolman.service.d
    state: directory
    mode: 0755
  tags:
    - image

- name: midolman systemd drop-in for disabling jmx listener
  copy:
    dest: /etc/systemd/system/midolman.service.d/jmxdisable.conf
    mode: 0644
    content: |
      [Service]
      Environment=JMXDISABLE=true
  tags:
    - image

- name: start midolman service
  systemd:
    daemon_reload: true
    enabled: true
    state: started
    name: midolman

