---
- name: configure permissive mode selinux
  selinux:
    policy: targeted
    state: permissive
  tags:
    - image

- name: install eucalyptus package
  yum:
    name: eucalyptus
    state: present
  tags:
    - image
    - packages

- name: eucalyptus configuration
  template:
    src: eucalyptus.conf.j2
    dest: /etc/eucalyptus/eucalyptus.conf
    owner: root
    group: root
    mode: 0644
