---
- name: eucalyptus zone/node keys get cloud-cert
  slurp:
    path: /var/lib/eucalyptus/keys/{{ zone_name }}/cloud-cert.pem
  delegate_to: "{{ groups.cloud[0] }}"
  register: slurp_result

- name: set eucalyptus zone/node keys cloud-cert fact
  set_fact: "eucalyptus_keys_{{ zone_name | replace('-','_') }}_cloud_cert='{{ slurp_result.content | b64decode }}'"

- name: eucalyptus zone/node keys get euca keystore
  slurp:
    path: /var/lib/eucalyptus/keys/euca.p12
  delegate_to: "{{ groups.cloud[0] }}"
  register: slurp_result

- name: set eucalyptus zone/node keys euca keystore fact
  set_fact: "eucalyptus_keys_{{ zone_name | replace('-','_') }}_euca_keystore='{{ slurp_result.content }}'"

- name: eucalyptus zone/node keys get cluster-cert
  slurp:
    path: /var/lib/eucalyptus/keys/{{ zone_name }}/cluster-cert.pem
  delegate_to: "{{ groups.cloud[0] }}"
  register: slurp_result

- name: set eucalyptus zone/node keys cluster-cert fact
  set_fact: "eucalyptus_keys_{{ zone_name | replace('-','_') }}_cluster_cert='{{ slurp_result.content | b64decode }}'"

- name: eucalyptus zone/node keys get cluster-pk
  slurp:
    path: /var/lib/eucalyptus/keys/{{ zone_name }}/cluster-pk.pem
  delegate_to: "{{ groups.cloud[0] }}"
  register: slurp_result

- name: set eucalyptus zone/node keys cluster-pk fact
  set_fact: "eucalyptus_keys_{{ zone_name | replace('-','_') }}_cluster_pk='{{ slurp_result.content | b64decode }}'"

- name: eucalyptus zone/node keys get node-cert
  slurp:
    path: /var/lib/eucalyptus/keys/{{ zone_name }}/node-cert.pem
  delegate_to: "{{ groups.cloud[0] }}"
  register: slurp_result

- name: set eucalyptus zone/node keys node-cert fact
  set_fact: "eucalyptus_keys_{{ zone_name | replace('-','_') }}_node_cert='{{ slurp_result.content | b64decode }}'"

- name: eucalyptus zone/node keys get node-pk
  slurp:
    path: /var/lib/eucalyptus/keys/{{ zone_name }}/node-pk.pem
  delegate_to: "{{ groups.cloud[0] }}"
  register: slurp_result

- name: set eucalyptus zone/node keys node-pk fact
  set_fact: "eucalyptus_keys_{{ zone_name | replace('-','_') }}_node_pk='{{ slurp_result.content | b64decode }}'"

