---
- import_tasks: yum_repos.yml
  tags:
    - image
    - packages

- import_tasks: yum_repos_vpcmido.yml
  tags:
    - image
    - packages
  when: net_mode == "VPCMIDO"

- import_tasks: host_facts.yml

- import_tasks: base_packages.yml

- import_tasks: base_config.yml

- name: zone key facts
  include_tasks: key_facts.yml
  with_items: "{{ groups.zone | map('extract', hostvars, ['eucalyptus_zone_name']) | list | unique | sort }}"
  loop_control:
    loop_var: zone_name
  when: key_facts
