---
- name: eucalyptus gpg key
  copy:
    src: RPM-GPG-KEY-eucalyptus-release
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-eucalyptus-release
    owner: root
    group: root
    mode: 0644

- name: install eucalyptus gpg key
  rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-eucalyptus-release

- name: eucalyptus appscale gpg key
  copy:
    src: RPM-GPG-KEY-eucalyptus-release-as
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-eucalyptus-release-as
    owner: root
    group: root
    mode: 0644

- name: install eucalyptus appscale gpg key
  rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-eucalyptus-release-as

- name: eucalyptus yum repository
  template:
    src: eucalyptus.repo.j2
    dest: /etc/yum.repos.d/eucalyptus.repo
    owner: root
    group: root
    mode: 0644

- name: euca2ools gpg key
  copy:
    src: RPM-GPG-KEY-euca2ools-release
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-euca2ools-release
    owner: root
    group: root
    mode: 0644

- name: install euca2ools gpg key
  rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-euca2ools-release

- name: euca2ools appscale gpg key
  copy:
    src: RPM-GPG-KEY-euca2ools-release-as
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-euca2ools-release-as
    owner: root
    group: root
    mode: 0644

- name: install euca2ools appscale gpg key
  rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-euca2ools-release-as

- name: euca2ools yum repository
  template:
    src: euca2ools.repo.j2
    dest: /etc/yum.repos.d/euca2ools.repo
    owner: root
    group: root
    mode: 0644

- name: enable epel yum repository
  yum:
    name: epel-release
    state: latest

- name: install epel gpg key
  rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7

- name: enable qemu enterprise virtualization yum repository
  yum:
    name: centos-release-qemu-ev
    state: latest

- name: install virtualization sig gpg key
  rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-Virtualization

