---
# console customization for ATS

- name: ats console static content nginx drop-in
  copy:
    src: nginx-ats-static.conf
    dest: /etc/eucaconsole/nginx.conf.d/40-nginx-ats-static.conf
    owner: root
    group: root
    mode: 0644

- name: ats console locale variant configuration
  replace:
    path: /etc/eucaconsole/console.ini
    regexp: '^#?\s*pyramid.default_locale_name\s*=.+$'
    replace: 'pyramid.default_locale_name = en@ATS'

- name: ats console locale negotiator configuration
  replace:
    path: /etc/eucaconsole/console.ini
    regexp: '^#?\s*pyramid.locale_negotiator\s*=.+$'
    replace: 'pyramid.locale_negotiator = eucaconsole.i18n.fixed_locale_negotiator'

- name: ats console footer product link configuration
  replace:
    path: /etc/eucaconsole/console.ini
    regexp: '^#?\s*product.url\s*=.+$'
    replace: 'product.url = {{ eucaconsole_ats_product_url }}'

